# -*- coding: utf-8 -*-
"""DataValidationFixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZT9bZbM1_0etQrWWEykopXo9usTTGGZ

# Suicide Research Dataset Analysis
This notebook performs a clean, professional analysis of the provided suicide research dataset. The focus is on publication trends, missing values, and informative visualizations.

---

## 1. Imports and Dataset Loading
"""
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from collections import Counter
import re

def main(file_path):
    # Set aesthetics
    sns.set(style="whitegrid", palette="muted", font_scale=1.2)

    # Load the dataset
    df = pd.read_csv(file_path + r"\v2.scrubbed_data.csv")

    print(f"Dataset contains {df.shape[0]:,} rows and {df.shape[1]:,} columns.")

    """## 2. Missing Value Analysis
    We'll inspect the dataset for missing values and highlight the top problematic columns.
    """

    # Columns to inspect
    columns_of_interest = [
        "combined_author_details", "author_affiliations", "journal_name", "publication_year",
        "language", "keywords", "doi", "research_methodology", "data_source",
        "grant_info", "suicide_prevention_measures", "abstract"
    ]


    # Subset dataframe
    df_copy = df[columns_of_interest].copy()

    # Normalize grant_info: treat blank or "none found" as missing
    df_copy['grant_info'] = df_copy['grant_info'].astype(str).str.strip().str.lower()
    df_copy['grant_info'] = df_copy['grant_info'].replace(['', 'none found'], pd.NA)

    # Normalize abstract: treat known placeholders as missing
    abstract_placeholders = {
        "<p>[abstract unavailable]</p>",
        "[abstract unavailable]",
        "<p>language: english</p>",
        "<p>[abstract unavailable]</p> <p>language: english</p>",
        "no abstract available.ko",
        "no abstract available",
        "no abstract was provided. however, the first page of this article is available by following the doi. en",
        "no abstract was provided. however, the first page of this article is available by following the doi. https://journals.lww.com/hrpjournal/citation/1999/07000/to_change_the_patient_or_the_patient_s_world__the.4.aspx en",
        "no abstract was provided. however, the first page of this article is available by following the doi. suicide selfr-harmen",
        "no abstract was provided. however, the first page of this article is available by following the doi.en"
    }

    df_copy['abstract'] = df_copy['abstract'].astype(str).str.strip().str.lower()
    df_copy['abstract'] = df_copy['abstract'].replace(abstract_placeholders, pd.NA)
    df_copy['abstract'] = df_copy['abstract'].replace('nan', pd.NA)  # Handle stringified NaNs

    # Compute missing counts and percentages
    total_rows = len(df_copy)
    missing_counts = df_copy.isnull().sum()
    missing_percent = (missing_counts / total_rows * 100).round(1)

    # Prepare DataFrame for plotting
    missing_df = pd.DataFrame({
        'Missing Count': missing_counts,
        'Missing %': missing_percent
    }).sort_values(by='Missing Count', ascending=False)

    # Plot
    plt.figure(figsize=(14, 6))
    ax = sns.barplot(x=missing_df.index, y=missing_df['Missing Count'], color="steelblue")

    # Add percentage labels
    for i, (count, pct) in enumerate(zip(missing_df['Missing Count'], missing_df['Missing %'])):
        ax.text(i, count + total_rows * 0.01, f"{pct}%", ha='center', va='bottom', fontsize=10)

    plt.title("Missing Values in Selected Key Columns", fontsize=14)
    plt.ylabel("Number of Missing Entries")
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

    """## 3. Publication Year Analysis
    Let's look at how research on suicide has evolved over time based on publication years.
    """

    # Clean up the publication year
    df['publication_year'] = pd.to_numeric(df['publication_year'], errors='coerce')
    df_years = df.dropna(subset=['publication_year'])

    plt.figure(figsize=(12, 6))
    sns.histplot(df_years['publication_year'], bins=30, kde=True)
    plt.title("Distribution of Publication Years")
    plt.xlabel("Publication Year")
    plt.ylabel("Number of Publications")
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    # Top publication years
    top_years = df_years['publication_year'].value_counts().head(10)
    print("Top 10 Most Frequent Publication Years:")
    print(top_years)

    """## 4. language Distribution
    Examine the distribution of article languages.
    """

    plt.figure(figsize=(10, 5))
    lang_counts = df['language'].value_counts().head(10)
    sns.barplot(x=lang_counts.index, y=lang_counts.values)
    plt.title("Top 10 languages Used in Publications")
    plt.xlabel("language")
    plt.ylabel("Count")
    plt.tight_layout()
    plt.show()

    """## 5. Grant Information Availability
    Check how many papers have associated grant data.
    """

    # Normalize and check grant information
    grant_col = df['grant_info'].fillna('').str.strip().str.lower()
    has_grant_info = ~grant_col.isin(['', 'none found'])

    # Count True (has grant) vs False (no grant)
    grant_info_counts = has_grant_info.value_counts()

    # Plot
    plt.figure(figsize=(6, 4))
    sns.barplot(
        x=grant_info_counts.index.map({True: 'Has Grant Info', False: 'No Grant Info'}),
        y=grant_info_counts.values
    )
    plt.title("Availability of Grant Information")
    plt.ylabel("Number of Articles")
    plt.tight_layout()
    plt.show()

    """## 6. Keyword Analysis (If Available)
    A simple frequency chart of the most common keywords.
    """

    if 'keywords' in df.columns and df['keywords'].notna().sum() > 0:
        dfk = df[df['keywords'] != r"['N\\A']"]
        all_keywords = dfk['keywords'].dropna().str.lower().str.split(', ')
        flat_keywords = []
        for sublist in all_keywords:
            for keyword in sublist:
                # Remove all punctuation except / and &
                cleaned = re.sub(r"[^\w\s/&]", "", keyword.strip())
                # Remove any remaining single quotes that might be left from original format
                cleaned = cleaned.replace("'", "")
                flat_keywords.append(cleaned)
        keyword_counts = Counter(flat_keywords)
        common_keywords = keyword_counts.most_common(20)

        keywords_df = pd.DataFrame(common_keywords, columns=["Keyword", "Count"])

        plt.figure(figsize=(12, 6))
        sns.barplot(data=keywords_df, x="Keyword", y="Count")
        plt.xticks(rotation=45)
        plt.title("Top 20 Most Common keywords")
        plt.tight_layout()
        plt.show()

        nankeys = df[df['keywords'] == r"['N\\A']"]
        nokeys = df[df['keywords'].isna()]
        kwmissing = pd.concat([nankeys, nokeys])
        print(f'Percent Missing keywords: {100 * (kwmissing.shape[0]/df.shape[0])}')
        print(f'Number missing keywords: {kwmissing.shape[0]}')

    """## 7. Save Cleaned DataFrame (Optional)"""

    # df.to_csv("cleaned_suicide_research_data.csv", index=False)
    # print("Cleaned data saved.")


if __name__ == '__main__':
    file_path = os.path.dirname(os.path.realpath(__file__)) + r'\safetylit_records'
    main(file_path)
