# -*- coding: utf-8 -*-
"""DOI Scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cpKcfnoM-zYOdapHQutoDHMWKue_9CRS
"""
import os
import pandas as pd
import requests
import time
import urllib.parse
from requests.exceptions import RequestException

# Function to clean titles for API queries
def clean_title(title):
    if isinstance(title, str):
        title = title.replace("&", "and")  # Replace ampersand
        title = title.replace("'", "")  # Remove single quotes
        title = title.replace('"', "")  # Remove double quotes
        title = title.replace("?", "")  # Remove question marks
        title = urllib.parse.quote(title)  # URL encode the title
    return title

# Function to fetch DOI from CrossRef API with retries
def get_doi_from_crossref(issn, title, max_retries=3):
    base_url = "https://api.crossref.org/works"
    query = f"?query.title={clean_title(title)}&filter=issn:{issn}"
    headers = {"User-Agent": "DOI-Finder/1.0 (mailto:your-email@example.com)"}

    for attempt in range(max_retries):
        try:
            response = requests.get(base_url + query, headers=headers, timeout=30)  # Increased timeout
            response.raise_for_status()
            data = response.json()

            if "message" in data and "items" in data["message"] and len(data["message"]["items"]) > 0:
                return data["message"]["items"][0].get("DOI", None)

        except RequestException as e:
            print(f"Error fetching DOI for ISSN {issn} and title {title} (Attempt {attempt+1}): {e}")
            time.sleep(5)  # Wait before retrying

    return None  # Return None if all attempts fail


def main(file_path):
    # Process missing DOIs
    df = pd.read_csv(file_path+ r'\v2.scrubbed_data.csv')

    for index, row in df.iterrows():
        if pd.isna(row["doi"]) and pd.notna(row["issn"]) and pd.notna(row.get("title")):
            doi = get_doi_from_crossref(row["issn"], row["title"])
            if doi:
                df.at[index, "doi"] = doi
            time.sleep(1)  # To avoid hitting API rate limits
    # Save dataset
    updated_doi_file_path = dir_path + "bibwithdoi.csv"
    df.to_csv(updated_doi_file_path, index=False)

    print(f"DOI retrieval complete! Updated dataset saved as {updated_doi_file_path}")

if __name__ == '__main__':
    # Load the dataset
    dir_path = os.path.dirname(os.path.realpath(__file__)) + r'\safetylit_records'

    main(dir_path)
