# -*- coding: utf-8 -*-
"""scraper8000to12000.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X0Ifq0EQSFpVqCaPnOjbD1L5tZfQbqjo
"""

import pandas as pd
import os
import requests
from bs4 import BeautifulSoup
import time
from IPython.display import display

def search_pubmed(title, retries=3, delay=5):
    """Searches PubMed for an article by title and extracts grant/funding information, with retry logic."""
    search_url = f'https://pubmed.ncbi.nlm.nih.gov/?term={title.replace(" ", "+")}'
    print(f"--- DEBUG: Results Page URL --- {search_url}")
    headers = {'User-Agent': 'Mozilla/5.0'}

    for attempt in range(retries):
        try:
            response = requests.get(search_url, headers=headers, timeout=10)
            response.raise_for_status()
            break
        except requests.exceptions.RequestException as e:
            print(f"Attempt {attempt+1} failed: {e}")
            time.sleep(delay)
    else:
        return None, "none found"

    soup = BeautifulSoup(response.text, 'html.parser')

    # Get first article link
    article_link = soup.find('a', {'class': 'docsum-title'})
    if not article_link:
        return None, "none found"

    article_url = 'https://pubmed.ncbi.nlm.nih.gov' + article_link.get('href', '')
    print(f"--- DEBUG: Article Page URL --- {article_url}")

    for attempt in range(retries):
        try:
            article_response = requests.get(article_url, headers=headers, timeout=10)
            article_response.raise_for_status()
            break
        except requests.exceptions.RequestException as e:
            print(f"Attempt {attempt+1} failed: {e}")
            time.sleep(delay)
    else:
        return article_url, "none found"

    article_soup = BeautifulSoup(article_response.text, 'html.parser')

    funding_section = article_soup.find('div', {'id': 'grants'})
    if not funding_section:
        print("--- DEBUG: Searching for alternative funding sections ---")
        funding_section = article_soup.find('section', string=lambda text: text and 'Funding' in text)
    if not funding_section:
        funding_section = article_soup.find('div', class_='funding-info')

    if not funding_section:
        print("--- DEBUG: Grants section not found! ---")
        funding_info = "none found"
    else:
        print("--- DEBUG: Grants section found! Extracting data... ---")
        funding_info = '\n'.join([
            f"Grant: {a.get('data-ga-label', a.text.strip())} | Details: {a.get('title', 'No details available')} | Text: {a.text.strip()} (Link: https://pubmed.ncbi.nlm.nih.gov{a.get('href', '')})"
            for a in funding_section.find_all(['a', 'div', 'p'])
        ])

    return article_url, funding_info

def main(file_path):
    df = pd.read_csv(file_path + r'\v2.scrubbed_data.csv')

    # Iterate through the titles in CSV
    df['PubMed_URL'] = "none found"
    df['ISSN'] = df.get('ISSN', 'none found')
    df['ISBN'] = df.get('ISBN', 'none found')
    df['Funding_Info'] = "none found"

    for i, title in enumerate(df['title']):  # Adjust index for correct row placement
        if pd.isna(title):
            continue

        url, funding = search_pubmed(title)
        df.at[i, 'PubMed_URL'] = url
        df.at[i, 'Funding_Info'] = funding

        print(f"Processed {i+1}/{len(df)}: {title}")
        time.sleep(2)  # Respectful delay to avoid being blocked

    # Display results as a DataFrame
    display(df)
    print("Scraping completed. Results displayed as DataFrame.")

    # Count the number of rows where 'Funding_Info' is not "none found"
    grant_count = (df['Funding_Info'] != "none found").sum()

    print(f"Total number of grant sections found: {grant_count}")

    # Define the output file path
    output_path = dir_path + r'\bibwithgrant.csv'

    # Save the DataFrame to a CSV file
    df.to_csv(output_path, index=False)

    print(f"Data saved successfully to {output_path}")

if __name__ == '__main__':
    # Define file path
    dir_path = os.path.dirname(os.path.realpath(__file__)) + r'\safetylit_records'


    # Load CSV into a DataFrame and get articles 8001 to 12000

    main(dir_path)
