# -*- coding: utf-8 -*-
"""Prevention updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Vdt933gHgv2QEvkZoiUEGlOILkL4T1B
"""
import matplotlib.pyplot as plt
import os
import pandas as pd
import spacy
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from collections import Counter
from langdetect import detect
from deep_translator import GoogleTranslator
from sklearn.feature_extraction.text import TfidfVectorizer


def check_removed_abstracts(df, unwanted_texts):
    remaining_unwanted = df[df['abstract'].str.lower().isin(unwanted_texts) | df['abstract'].str.strip().eq("") | df['abstract'].isna()]
    if remaining_unwanted.empty:
        print("All unwanted and blank abstracts have been successfully removed.")
    else:
        print("Some unwanted abstracts remain in the dataset:")
        print(remaining_unwanted[['title', 'abstract']])


# Function to detect language and translate if necessary
def translate_to_english(text):
    try:
        detected_lang = detect(text)  # Detect language
        if detected_lang != "en":  # Only translate non-English abstracts
            translated_text = GoogleTranslator(source='auto', target='en').translate(text)
            if translated_text and translated_text.lower() != text.lower():  # Ensure translation changed the text
                return translated_text, True  # Return translated text and flag
        return text, False  # Return original text and flag
    except Exception as e:
        return text, False  # If detection or translation fails, return original


# Function to count and display translated abstracts
def count_translated_abstracts(df):
    translated_df = df[df['was_translated']]
    print(f"Number of abstracts translated: {len(translated_df)}")
    if not translated_df.empty:
        print("titles of translated abstracts:")
        print(translated_df[['title', 'abstract', 'translated_abstract']].head(10))  # Show first 10 for review


# Function to download translated abstracts for manual review
def download_translated_abstracts_csv(df):
    translated_df = df[['title', 'abstract', 'translated_abstract', 'was_translated']]
    translated_df.to_csv(dir_path + r'\translated_abstracts_for_review.csv', index=False)
    print("Translated abstracts saved as 'translated_abstracts_for_review.csv'")


# Preprocessing function
def preprocess_text(text):
    if pd.isna(text):
        return ""
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)  # Remove special characters
    return text

# Apply preprocessing


# Tokenization and stopword removal
def tokenize_text(text):
    nlp = spacy.load("en_core_web_sm")
    doc = nlp(text)
    tokens = [token.lemma_ for token in doc if not token.is_stop and token.is_alpha]  # Remove stopwords & keep words only
    return " ".join(tokens)

# Apply tokenization


# Function to download tokenized abstracts
def download_tokenized_csv(df):
    tokenized_df = df[['title', 'abstract', 'translated_abstract', 'cleaned_abstract', 'tokenized_abstract']]
    tokenized_df.to_csv(dir_path + r'\tokenized_abstracts.csv', index=False)
    print("Tokenized abstracts saved as 'tokenized_abstracts.csv'")


# Comprehensive List of Suicide Prevention and Mental Health Treatment Keywords



# Function to extract suicide prevention methods using keyword matching
def extract_prevention_methods(text, prevention_keywords):
    found_methods = [word for word in prevention_keywords if word in text.lower()]
    return ", ".join(set(found_methods)) if found_methods else None  # Remove duplicates


# Function to extract prevention-related terms using regex
def extract_prevention_methods2(text, therapy_pattern, crisis_services_pattern, medication_pattern, holistic_pattern, medical_terms_pattern):
    therapy_matches = re.findall(therapy_pattern, text, flags=re.IGNORECASE)
    crisis_matches = re.findall(crisis_services_pattern, text, flags=re.IGNORECASE)
    medication_matches = re.findall(medication_pattern, text, flags=re.IGNORECASE)
    holistic_matches = re.findall(holistic_pattern, text, flags=re.IGNORECASE)
    medical_terms_matches = re.findall(medical_terms_pattern, text, flags=re.IGNORECASE)

    all_matches = list(set(therapy_matches + crisis_matches + medication_matches + holistic_matches + medical_terms_matches))  # Remove duplicates
    return ", ".join(all_matches) if all_matches else None


def main(file_path):
    # 1️⃣ Therapy and Treatment Methods
    therapy_pattern = r"\b(?:cognitive behavioral therapy|cbt|dialectical behavior therapy|dbt|psychodynamic therapy|interpersonal therapy|family therapy|group therapy|supportive counseling|motivational interviewing|problem-solving therapy|mindfulness-based cognitive therapy|talk therapy|psychotherapy|counseling|therapy|analysis|healing|remedy|therapeutics|mental therapy|personal therapy|spiritual therapy|psychosomatic therapy|telepathic therapy|psychic therapy|mental treatment|counseling psychology|mental health therapy|psychiatric counseling|psychiatric therapy|psychological therapy|psychiatric care|psychological support|mental health services|depression treatment|self-harm prevention|substance abuse treatment)\b"

    # 2️⃣ Crisis Intervention Services
    crisis_services_pattern = r"\b(?:suicide prevention hotline|crisis intervention teams|emergency psychiatric services|mobile crisis units|peer support programs|safety planning|crisis stabilization units|24/7 crisis text lines|community mental health centers|assertive community treatment|act teams)\b"

    # 3️⃣ Pharmaceuticals & Medications
    medication_pattern = r"\b(?:fluoxetine|prozac|sarafem|sertraline|zoloft|citalopram|celexa|escitalopram|lexapro|paroxetine|paxil|seroxat|fluvoxamine|luvox|venlafaxine|effexor|duloxetine|cymbalta|desvenlafaxine|pristiq|levomilnacipran|fetzima|amitriptyline|elavil|endep|nortriptyline|pamelor|desipramine|norpramin|imipramine|tofranil|clomipramine|anafranil|doxepin|sinequan|trimipramine|surmontil|protriptyline|vivactil|phenelzine|nardil|tranylcypromine|parnate|isocarboxazid|marplan|selegiline|emsam|bupropion|wellbutrin|zyban|mirtazapine|remeron|nefazodone|serzone|trazodone|desyrel|oleptro|vilazodone|viibryd|vortioxetine|trintellix|haloperidol|haldol|chlorpromazine|thorazine|fluphenazine|prolixin|perphenazine|trilafon|thioridazine|mellaril|thiothixene|navane|loxapine|loxitane|pimozide|orap|trifluoperazine|stelazine|risperidone|risperdal|olanzapine|zyprexa|quetiapine|seroquel|aripiprazole|abilify|ziprasidone|geodon|clozapine|clozaril|paliperidone|invega|asenapine|saphris|lurasidone|latuda|iloperidone|fanapt|brexpiprazole|rexulti|cariprazine|vraylar|lithium|lithobid|lamotrigine|lamictal|valproate|depakote|divalproex sodium|carbamazepine|tegretol|oxcarbazepine|trileptal|gabapentin|neurontin|topiramate|topamax|alprazolam|xanax|lorazepam|ativan|diazepam|valium|clonazepam|klonopin|chlordiazepoxide|librium|clorazepate|tranxene|oxazepam|serax|temazepam|restoril|triazolam|halcion|buspirone|buspar|hydroxyzine|atarax|vistaril|pregabalin|lyrica|meprobamate|miltown|equanil|propranolol|inderal|prazosin|minipress|methylphenidate|ritalin|concerta|daytrana|metadate|aptensio|dexmethylphenidate|focalin|amphetamine|adderall|mydayis|evekeo|dextroamphetamine|dexedrine|vyvanse|lisdexamfetamine|desoxyn|methamphetamine|zolpidem|ambien|eszopiclone|lunesta|zaleplon|sonata|ramelteon|rozerem|suvorexant|belsomra|trazodone|desyrel|doxepin|silenor|atomoxetine|strattera|guanfacine|intuniv|clonidine|kapvay|modafinil|provigil|armodafinil|nuvigil)\b"

    # 4️⃣ Holistic & Alternative Therapies
    holistic_pattern = r"\b(?:acupuncture|meditation|mindfulness|yoga|tai chi|qigong|herbal medicine|chinese medicine|ayurveda|homeopathy|naturopathy|aromatherapy|massage therapy|reiki|energy healing|hypnotherapy|chiropractic care|sound therapy|music therapy|art therapy|animal-assisted therapy|equine therapy|nature therapy|forest bathing|holistic nutrition|functional medicine|integrative medicine|breathwork|progressive muscle relaxation|guided imagery|biofeedback|light therapy|sensory deprivation therapy|float therapy|spiritual counseling|faith-based therapy|psychoneuroimmunology|vagus nerve stimulation|ayahuasca therapy|psilocybin-assisted therapy|mdma-assisted therapy|ketamine therapy|microdosing|craniosacral therapy|somatic therapy|rolfing|feldenkrais method|alexander technique)\b"

    # 5️⃣ Medical Terminology Related to Mental Health
    medical_terms_pattern = r"\b(?:electroconvulsive therapy|ect|repetitive transcranial magnetic stimulation|rtms|ketamine therapy|psychiatric hospitalization|involuntary commitment|partial hospitalization program|intensive outpatient program|iop|behavioral activation|exposure therapy|systematic desensitization|schema therapy|attachment-based therapy)\b"

    prevention_keywords = [
        # Psychotherapies and Counseling Approaches
        "cognitive behavioral therapy", "cbt", "dialectical behavior therapy", "dbt",
        "psychodynamic therapy", "interpersonal therapy", "family therapy",
        "group therapy", "supportive counseling", "motivational interviewing",
        "problem-solving therapy", "mindfulness-based cognitive therapy",
        "talk therapy", "psychotherapy", "counseling", "therapy", "analysis",
        "healing", "remedy", "therapeutics", "mental therapy", "personal therapy",
        "spiritual therapy", "psychosomatic therapy", "telepathic therapy",
        "psychic therapy", "mental treatment", "counseling psychology",
        "mental health therapy", "psychiatric counseling", "psychiatric therapy",
        "psychological therapy", "psychiatric care", "psychological support",
        "mental health services", "crisis intervention", "depression treatment",
        "self-harm prevention", "substance abuse treatment",

        # Crisis Intervention and Support Services
        "suicide prevention hotline", "crisis intervention teams", "emergency psychiatric services",
        "mobile crisis units", "peer support programs", "safety planning",
        "crisis stabilization units", "24/7 crisis text lines",
        "community mental health centers", "assertive community treatment", "act teams",

        # Pharmaceuticals for Mental Health
        ## Antidepressants
        # SSRIs
        "fluoxetine", "prozac", "sarafem", "sertraline", "zoloft", "citalopram", "celexa",
        "escitalopram", "lexapro", "paroxetine", "paxil", "seroxat", "fluvoxamine", "luvox",
        # SNRIs
        "venlafaxine", "effexor", "duloxetine", "cymbalta", "desvenlafaxine", "pristiq",
        "levomilnacipran", "fetzima",
        # TCAs
        "amitriptyline", "elavil", "endep", "nortriptyline", "pamelor", "desipramine", "norpramin",
        "imipramine", "tofranil", "clomipramine", "anafranil", "doxepin", "sinequan", "trimipramine",
        "surmontil", "protriptyline", "vivactil",
        # MAOIs
        "phenelzine", "nardil", "tranylcypromine", "parnate", "isocarboxazid", "marplan",
        "selegiline", "emsam",

        ## Atypical Antidepressants
        "bupropion", "wellbutrin", "zyban", "mirtazapine", "remeron", "nefazodone", "serzone",
        "trazodone", "desyrel", "oleptro", "vilazodone", "viibryd", "vortioxetine", "trintellix",

        ## Antipsychotics
        # Typical Antipsychotics
        "haloperidol", "haldol", "chlorpromazine", "thorazine", "fluphenazine", "prolixin",
        "perphenazine", "trilafon", "thioridazine", "mellaril", "thiothixene", "navane",
        "loxapine", "loxitane", "pimozide", "orap", "trifluoperazine", "stelazine",
        # Atypical Antipsychotics
        "risperidone", "risperdal", "olanzapine", "zyprexa", "quetiapine", "seroquel",
        "aripiprazole", "abilify", "ziprasidone", "geodon", "clozapine", "clozaril",
        "paliperidone", "invega", "asenapine", "saphris", "lurasidone", "latuda",
        "iloperidone", "fanapt", "brexpiprazole", "rexulti", "cariprazine", "vraylar",

        ## Mood Stabilizers
        "lithium", "lithobid", "lamotrigine", "lamictal", "valproate", "depakote",
        "divalproex sodium", "carbamazepine", "tegretol", "oxcarbazepine", "trileptal",
        "gabapentin", "neurontin", "topiramate", "topamax",

        ## Anti-Anxiety Medications
        # Benzodiazepines
        "alprazolam", "xanax", "lorazepam", "ativan", "diazepam", "valium",
        "clonazepam", "klonopin", "chlordiazepoxide", "librium", "clorazepate", "tranxene",
        "oxazepam", "serax", "temazepam", "restoril", "triazolam", "halcion",
        # Non-Benzodiazepine Anxiolytics
        "buspirone", "buspar", "hydroxyzine", "atarax", "vistaril", "pregabalin", "lyrica",
        "meprobamate", "miltown", "equanil", "propranolol", "inderal", "prazosin", "minipress",

        ## Stimulants (for ADHD and related conditions)
        "methylphenidate", "ritalin", "concerta", "daytrana", "metadate", "aptensio",
        "dexmethylphenidate", "focalin", "amphetamine", "adderall", "mydayis", "evekeo",
        "dextroamphetamine", "dexedrine", "vyvanse", "lisdexamfetamine", "desoxyn", "methamphetamine",

        ## Sleep Aids
        "zolpidem", "ambien", "eszopiclone", "lunesta", "zaleplon", "sonata",
        "ramelteon", "rozerem", "suvorexant", "belsomra", "trazodone", "desyrel",
        "doxepin", "silenor", "mirtazapine", "remeron",

        ## Other Medications
        "atomoxetine", "strattera", "guanfacine", "intuniv", "clonidine", "kapvay",
        "modafinil", "provigil", "armodafinil", "nuvigil",

        # General Suicide Prevention Terms
        "suicide prevention", "mental health program", "psychiatric care",
        "psychological support", "mental health services", "crisis intervention",
        "depression treatment", "self-harm prevention", "substance abuse treatment",

        # Medical Terminology Related to Mental Health
        "electroconvulsive therapy", "ect", "repetitive transcranial magnetic stimulation",
        "rtms", "ketamine therapy", "psychiatric hospitalization", "involuntary commitment",
        "partial hospitalization program", "intensive outpatient program", "iop",
        "behavioral activation", "exposure therapy", "systematic desensitization",
        "schema therapy", "attachment-based therapy"

        ## Holistic and Alternative Therapies
        "acupuncture", "meditation", "mindfulness", "yoga", "tai chi", "qigong",
        "herbal medicine", "chinese medicine", "ayurveda", "homeopathy", "naturopathy",
        "aromatherapy", "massage therapy", "reiki", "energy healing", "hypnotherapy",
        "chiropractic care", "sound therapy", "music therapy", "art therapy",
        "animal-assisted therapy", "equine therapy", "nature therapy", "forest bathing",
        "holistic nutrition", "functional medicine", "integrative medicine",
        "breathwork", "progressive muscle relaxation", "guided imagery",
        "biofeedback", "light therapy", "sensory deprivation therapy",
        "float therapy", "spiritual counseling", "faith-based therapy",
        "psychoneuroimmunology", "vagus nerve stimulation", "ayahuasca therapy",
        "psilocybin-assisted therapy", "mdma-assisted therapy", "ketamine therapy",
        "microdosing", "craniosacral therapy", "somatic therapy", "rolfing",
        "feldenkrais method", "alexander technique"
    ]

    df = pd.read_csv(file_path + r'\v2.scrubbed_data.csv')

    unwanted_texts = [
        "no abstract available.ko",
        "no abstract available",
        "no abstract was provided. however, the first page of this article is available by following the doi. en",
        "no abstract was provided. however, the first page of this article is available by following the doi. https://journals.lww.com/hrpjournal/citation/1999/07000/to_change_the_patient_or_the_patient_s_world__the.4.aspx en",
        "no abstract was provided. however, the first page of this article is available by following the doi. suicide selfr-harmen",
        "no abstract was provided. however, the first page of this article is available by following the doi.en",
        "no abstract was provided. however, the first page of this article is available by following the doi.en"
    ]
    df = df[~df['abstract'].isin(unwanted_texts)]  # Remove exact matches
    df = df[df['abstract'].str.strip() != ""]  # Remove completely blank abstracts
    df = df.dropna(subset=['abstract'])  # Remove NaN values

    check_removed_abstracts(df, unwanted_texts)

    print(df[['abstract']].head(10))  # Display the first 10 rows of the 'abstract' column
    print(df['abstract'].isna().sum())  # Count missing values in 'abstract'

    df[['translated_abstract', 'was_translated']] = df['abstract'].astype(str).apply(lambda x: pd.Series(translate_to_english(x)))

    count_translated_abstracts(df)

    download_translated_abstracts_csv(df)

    df['cleaned_abstract'] = df['translated_abstract'].apply(preprocess_text)

    df['tokenized_abstract'] = df['cleaned_abstract'].apply(tokenize_text)

    download_tokenized_csv(df)

    # Remove duplicate abstracts after tokenization
    df = df.drop_duplicates(subset=['tokenized_abstract'])

    # Save the updated tokenized CSV
    download_tokenized_csv(df)

    # TF-IDF Vectorization
    vectorizer = TfidfVectorizer(max_features=20, stop_words='english')  # Extract top 20 keywords
    tfidf_matrix = vectorizer.fit_transform(df['tokenized_abstract'])

    # Get top keywords
    feature_names = vectorizer.get_feature_names_out()
    tfidf_scores = tfidf_matrix.sum(axis=0).A1  # Sum TF-IDF scores across all documents

    # Convert to DataFrame
    tfidf_df = pd.DataFrame({'Keyword': feature_names, 'Score': tfidf_scores})
    tfidf_df = tfidf_df.sort_values(by="Score", ascending=False)

    # Display top keywords
    print(tfidf_df)

    # Save the results to a CSV file for manual review
    tfidf_df.to_csv(dir_path + r'\tfidf_keywords.csv', index=False)
    print("TF-IDF keywords saved as 'tfidf_keywords.csv'")

    # Apply the function to tokenized abstracts
    df['prevention_methods'] = df['tokenized_abstract'].apply(extract_prevention_methods)

    # Display extracted prevention methods
    print(df[['title', 'tokenized_abstract', 'prevention_methods']].head(10))

    # Save extracted prevention methods for manual review
    df[['title', 'tokenized_abstract', 'prevention_methods']].to_csv(dir_path + r'\prevention_methods.csv', index=False)
    print("Extracted prevention methods saved as 'prevention_methods.csv'")

    # Apply the regex function to each tokenized abstract
    df['extracted_prevention_methods'] = df['tokenized_abstract'].apply(lambda x: extract_prevention_methods2(x) if isinstance(x, str) else None)

    # Display sample results
    print(df[['title', 'tokenized_abstract', 'extracted_prevention_methods']].head(10))

    # Save extracted methods for review
    df[['title', 'tokenized_abstract', 'extracted_prevention_methods']].to_csv(dir_path + r'\extracted_prevention_methods.csv', index=False)
    print("Extracted prevention methods saved as 'extracted_prevention_methods.csv'")

    # Display first few rows of the prevention methods frequency
    all_methods = []
    for methods in df['extracted_prevention_methods'].dropna():
        all_methods.extend([m.strip() for m in methods.split(",")])

    method_counts = Counter(all_methods)
    method_counts_df = pd.DataFrame(method_counts.items(), columns=['Method', 'Count']).sort_values('Count', ascending=False)

    print(method_counts_df.head(20))

    # Plot top 20 prevention methods
    top_n = 20
    top_methods = method_counts_df.head(top_n)

    plt.figure(figsize=(12, 6))
    plt.barh(top_methods['Method'], top_methods['Count'], color='skyblue')
    plt.xlabel("Frequency")
    plt.ylabel("Prevention Method")
    plt.title(f"Top {top_n} Suicide Prevention Methods")
    plt.gca().invert_yaxis()  # Reverse order for readability
    plt.show()


if __name__ == '__main__':
    dir_path = os.path.dirname(os.path.realpath(__file__)) + r'\safetylit_records'

    main()
