# -*- coding: utf-8 -*-
"""SingleYearNLPFINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPPC2NTt6RRvWx-Q62fu3eaRm50mEIij
"""

# Install and download models in Colab
!pip install -q spacy textblob wordcloud openpyxl nrclex pyvis sentence-transformers
!python -m textblob.download_corpora
!python -m spacy download en_core_web_sm

import pandas as pd, spacy

# Load spaCy model
nlp = spacy.load('en_core_web_sm')

# 1) Read the new CSV
raw_df = pd.read_csv('/content/v4.2004_complete_data.csv')

# 2) Drop any completely empty columns
df = raw_df.dropna(axis=1, how='all')

# 3) Standardize all column names to lowercase with underscores,
#    so downstream code (e.g. df['abstract'], df['publication_year']) still works.
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(' ', '_')
      .str.replace('-', '_')
)

# 4) Split 'combined_author_details' into individual author_details.* columns
df['combined_author_details'] = df['combined_author_details'].astype(str)
authors_split = df['combined_author_details'].str.split(';', expand=True)
authors_split.columns = [f'author_details.{i+1}' for i in range(authors_split.shape[1])]
df = pd.concat([df, authors_split], axis=1)

# Now df has the same ‘author_details.1’, ‘author_details.2’, … columns
# that the rest of your notebook expects.
df.head()

# — Cell 2: Trim author_details & fix types —

# 1) Drop any author_details beyond the first 10 co‑authors
author_cols_to_drop = [
    col for col in df.columns
    if col.startswith('author_details.') and int(col.split('.')[-1]) > 10
]
df.drop(columns=author_cols_to_drop, inplace=True)

# 2) Ensure abstracts are strings (replace missing with empty string)
df['abstract'] = df['abstract'].fillna('').astype(str)

# 3) Cast publication_year to numeric (so plotting by year works)
df['publication_year'] = (
    pd.to_numeric(df['publication_year'], errors='coerce')
      .astype('Int64')
)

# Preview
df.head()

# — Cell 3: Missing-values & Abstract-length exploration —

import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

# 1) Missing-values heatmap
plt.figure(figsize=(12, 6))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title('Missing Values Across Columns')
plt.xlabel('Columns')
plt.ylabel('Row Index')
plt.show()

# 2) Abstract-length distribution
df['abstract_length'] = df['abstract'].str.len()

fig = px.box(
    df,
    y='abstract_length',
    points='all',
    title='Abstract Length Distribution'
)
fig.show()

# 3) Outlier detection (1.5×IQR rule)
q1 = df['abstract_length'].quantile(0.25)
q3 = df['abstract_length'].quantile(0.75)
iqr = q3 - q1
upper_bound = q3 + 1.5 * iqr

outlier_count = df['abstract_length'].gt(upper_bound).sum()
print(f"Abstract-length outliers (# docs > {upper_bound:.0f} chars): {outlier_count}")

# — Cell 4: From WordCloud through Topic Modeling & Clustering —

from wordcloud import WordCloud
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation, PCA
from sklearn.cluster import KMeans
import plotly.express as px

# 1) Word Cloud of all abstracts
all_text = ' '.join(df['abstract'].dropna())
wc = WordCloud(width=800, height=400, background_color='white').generate(all_text)
plt.figure(figsize=(15, 7))
plt.imshow(wc, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud of Abstract Texts')
plt.show()

# 2) TF‑IDF vectorization
tfidf = TfidfVectorizer(max_features=1000, stop_words='english')
X = tfidf.fit_transform(df['abstract'])

# 3) LDA topic modeling
lda = LatentDirichletAllocation(n_components=5, random_state=42)
lda.fit(X)

for idx, comp in enumerate(lda.components_, start=1):
    terms = tfidf.get_feature_names_out()
    top_terms = [terms[i] for i in comp.argsort()[-10:]]
    print(f"Topic {idx}: {top_terms}")

# 4) K‑Means clustering
kmeans = KMeans(n_clusters=5, random_state=42)
df['cluster'] = kmeans.fit_predict(X)

# 5) PCA for 2D visualization
pca = PCA(n_components=2, random_state=42)
coords = pca.fit_transform(X.toarray())
df['pca1'], df['pca2'] = coords[:, 0], coords[:, 1]

fig = px.scatter(
    df,
    x='pca1',
    y='pca2',
    color=df['cluster'].astype(str),
    title='Abstract Clusters (KMeans + PCA)'
)
fig.show()

# — Cell 5: NER Label Frequency —

from collections import Counter
import seaborn as sns
import matplotlib.pyplot as plt

# Take a reproducible sample of abstracts
sample_text = ' '.join(
    df['abstract']
      .dropna()
      .sample(50, random_state=42)
)

# Run spaCy NER
doc = nlp(sample_text)
labels = [ent.label_ for ent in doc.ents]

# Count label occurrences
freq = Counter(labels)

# Plot
plt.figure(figsize=(10, 6))
sns.barplot(x=list(freq.keys()), y=list(freq.values()))
plt.title('NER Label Frequency (50‑abstract sample)')
plt.xlabel('Entity Type')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# — Cell 6: Sentiment Polarity & Publication Trends —

from textblob import TextBlob
import seaborn as sns
import matplotlib.pyplot as plt

# 1) Compute sentiment scores
df['polarity'] = df['abstract'].apply(lambda x: TextBlob(x).sentiment.polarity)
df['subjectivity'] = df['abstract'].apply(lambda x: TextBlob(x).sentiment.subjectivity)

# 2) Plot polarity distribution
plt.figure(figsize=(10, 6))
sns.histplot(df['polarity'], bins=30, kde=True)
plt.title('Sentiment Polarity Distribution')
plt.xlabel('Polarity')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

# 3) Plot number of publications by year
yearly_counts = df['publication_year'].value_counts().sort_index()

plt.figure(figsize=(10, 6))
plt.plot(yearly_counts.index, yearly_counts.values, marker='o')
plt.title('Publications by Year')
plt.xlabel('Year')
plt.ylabel('Number of Publications')
plt.grid(True)
plt.tight_layout()
plt.show()

# — Cell 7: Co-authorship Network & Prolific Authors —

import networkx as nx
import matplotlib.pyplot as plt
from collections import Counter
import pandas as pd

# 1) Identify all author_details columns
author_cols = [col for col in df.columns if col.startswith('author_details.')]

# 2) Build the co-authorship graph
G = nx.Graph()
for _, row in df.iterrows():
    authors = [row[col] for col in author_cols if pd.notna(row[col]) and row[col] != '']
    for i in range(len(authors)):
        for j in range(i+1, len(authors)):
            G.add_edge(authors[i], authors[j])

# 3) Plot the network
plt.figure(figsize=(12, 12))
pos = nx.spring_layout(G, k=0.5, seed=42)
nx.draw(G, pos, node_size=30, edge_color='gray', with_labels=False)
plt.title('Co-authorship Network Graph')
plt.axis('off')
plt.show()

# 4) Compute prolific authors (more than one publication)
all_authors = df[author_cols].values.ravel()
all_authors = pd.Series(all_authors).dropna().astype(str)
author_counts = Counter(all_authors)
prolific = {author: count for author, count in author_counts.items() if count > 1}

# 5) Create a DataFrame and display top 20
prolific_df = (
    pd.DataFrame.from_dict(prolific, orient='index', columns=['publications'])
      .sort_values('publications', ascending=False)
      .rename_axis('author')
      .reset_index()
)
print("Top Prolific Authors:")
display(prolific_df.head(20))

# — Cell 8: Emotion Detection per Prolific Author —

from nrclex import NRCLex
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter

# 1) Rebuild an author-level table with combined abstracts
records = []
author_cols = [c for c in df.columns if c.startswith('author_details.')]

for author, count in prolific.items():
    # find all rows where this author appears
    mask = df[author_cols].eq(author).any(axis=1)
    abstracts = df.loc[mask, 'abstract'].dropna().astype(str)
    combined = ' '.join(abstracts)
    records.append({
        'author': author,
        'publications': count,
        'text': combined
    })

author_df = pd.DataFrame(records)

# 2) Emotion extraction function
def detect_emotions(text):
    try:
        return NRCLex(text).raw_emotion_scores
    except:
        return {}

# 3) Apply to each author’s combined text
author_df['emotion_scores'] = author_df['text'].apply(detect_emotions)

# 4) Expand into separate columns
emotions = pd.DataFrame(author_df['emotion_scores'].tolist()).fillna(0).astype(int)
author_df = pd.concat([author_df.drop(columns='emotion_scores'), emotions], axis=1)

# 5) Show top‑5 authors by ‘joy’
print("Top 5 Prolific Authors by Joy:")
display(author_df.sort_values('joy', ascending=False)[
    ['author', 'publications', 'joy']
].head(5))

# 6) Plot average emotion across all prolific authors
avg_emotions = emotions.mean().sort_values(ascending=False)

plt.figure(figsize=(8, 5))
avg_emotions.plot(kind='bar')
plt.title('Average Emotion Scores (Prolific Authors)')
plt.xlabel('Emotion')
plt.ylabel('Average Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# — Cell 9: Journal Publication Breakdown: Prolific vs Non‑Prolific —

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# 1) Identify rows with any prolific author
author_cols = [col for col in df.columns if col.startswith('author_details.')]
mask_prolific_rows = df[author_cols].isin(prolific.keys()).any(axis=1)
prolific_rows_df = df.loc[mask_prolific_rows].copy()
non_prolific_df   = df.loc[~mask_prolific_rows].copy()

# 2) Count documents per journal
prolific_counts     = prolific_rows_df['journal_name'].value_counts().rename('prolific_count')
non_prolific_counts = non_prolific_df['journal_name'].value_counts().rename('non_prolific_count')

# 3) Merge and compute totals and percentages
journal_merged = pd.concat([prolific_counts, non_prolific_counts], axis=1).fillna(0)
journal_merged['total']             = journal_merged['prolific_count'] + journal_merged['non_prolific_count']
journal_merged['percent_prolific']  = (journal_merged['prolific_count'] / journal_merged['total']) * 100

# 4) Filter journals with at least 5 papers
filtered = journal_merged[journal_merged['total'] >= 5]

# 5) Plot top 20 journals by % prolific authors
plt.figure(figsize=(12, 6))
sns.barplot(
    x=filtered['percent_prolific'].head(20),
    y=filtered.index[:20],
    palette='Blues_d'
)
plt.title('% of Publications by Prolific Authors per Journal (min 5 papers)')
plt.xlabel('% Prolific Authors')
plt.ylabel('Journal')
plt.tight_layout()
plt.show()

# — Cell 10: Sentiment Polarity by Journal (Prolific Authors) —

import seaborn as sns
import matplotlib.pyplot as plt

# 1) Compute average polarity by journal for prolific authors
sentiment_by_journal = prolific_rows_df.groupby('journal_name')['polarity'].mean()

# 2) Sort and select bottom and top 10 journals
sentiment_sorted = sentiment_by_journal.sort_values()
bottom10 = sentiment_sorted.head(10)
top10    = sentiment_sorted.tail(10)

# 3) Plot
plt.figure(figsize=(14, 6))
sns.barplot(x=bottom10.values, y=bottom10.index, color='salmon', label='Lowest Polarity')
sns.barplot(x=top10.values,    y=top10.index,    color='skyblue', label='Highest Polarity')
plt.axvline(0, color='gray', linestyle='--')
plt.title('Average Sentiment Polarity by Journal — Prolific Authors')
plt.xlabel('Average Polarity')
plt.ylabel('Journal Name')
plt.legend()
plt.tight_layout()
plt.show()

# — Cell 11: Sentiment Polarity Comparison: Prolific vs Non‑Prolific —

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from textblob import TextBlob
import numpy as np

# 1) Recompute the two groups if needed
author_cols      = [c for c in df.columns if c.startswith('author_details.')]
mask_prolific    = df[author_cols].isin(prolific.keys()).any(axis=1)
prolific_df      = df.loc[mask_prolific].copy()
non_prolific_df  = df.loc[~mask_prolific].copy()

# 2) Compute sentiment polarity
prolific_df['polarity']     = prolific_df['abstract'].apply(lambda x: TextBlob(str(x)).sentiment.polarity)
non_prolific_df['polarity'] = non_prolific_df['abstract'].apply(lambda x: TextBlob(str(x)).sentiment.polarity)

# 3) Build a long-form DataFrame
comp_df = pd.DataFrame({
    'polarity': np.concatenate([prolific_df['polarity'], non_prolific_df['polarity']]),
    'group':    ['Prolific']*len(prolific_df) + ['Non‑Prolific']*len(non_prolific_df)
})

# 4) Plot
plt.figure(figsize=(10, 6))
sns.boxplot(
    x='group',
    y='polarity',
    data=comp_df,
    palette={'Prolific':'skyblue','Non‑Prolific':'salmon'}
)
plt.title('Sentiment Polarity Distribution: Prolific vs Non‑Prolific Authors')
plt.xlabel('')
plt.ylabel('Polarity')
plt.tight_layout()
plt.show()

# — Cell 12: Average Sentiment Heatmap by Journal —

import seaborn as sns
import matplotlib.pyplot as plt

# 1) Compute average polarity & subjectivity per journal (prolific authors)
sentiment_by_journal = (
    prolific_df
    .groupby('journal_name')[['polarity', 'subjectivity']]
    .mean()
)

# 2) Keep journals with at least 3 papers
counts = prolific_df['journal_name'].value_counts()
eligible = counts[counts >= 3].index
sentiment_by_journal = sentiment_by_journal.loc[eligible]

# 3) Plot heatmap
plt.figure(figsize=(10, 8))
sns.heatmap(
    sentiment_by_journal,
    annot=False,
    fmt=".2f",
    cmap="coolwarm",
    cbar_kws={'label': 'Score'}
)
plt.title('Avg Sentiment (Polarity & Subjectivity) by Journal\n(Prolific Authors, ≥3 papers)')
plt.xlabel('Sentiment Metric')
plt.ylabel('Journal')
plt.tight_layout()
plt.show()

# — Cell 13: Emotion Proportions by Journal —

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from nrclex import NRCLex

# Define the eight NRC emotion columns
emotion_cols = [
    'anger', 'anticipation', 'disgust', 'fear',
    'joy', 'sadness', 'surprise', 'trust'
]

# 0) Compute row‑level emotion scores (if not already present)
#    This builds a small DF of shape (n_rows × 8)
row_emotions = (
    df['abstract']
      .fillna('')
      .astype(str)
      .apply(lambda text: pd.Series(NRCLex(text).raw_emotion_scores))
      .fillna(0)
      .astype(int)
)

# 1) Concatenate these back onto df
df_em = pd.concat([df, row_emotions[emotion_cols]], axis=1)

# 2) Re‑split into prolific vs non‑prolific rows
author_cols      = [c for c in df_em.columns if c.startswith('author_details.')]
mask_prolific    = df_em[author_cols].isin(prolific.keys()).any(axis=1)
prol_em_df       = df_em.loc[mask_prolific]
non_prol_em_df   = df_em.loc[~mask_prolific]

# 3) Sum emotions per journal
emo_pro = prol_em_df.groupby('journal_name')[emotion_cols].sum()
emo_non = non_prol_em_df.groupby('journal_name')[emotion_cols].sum()

# 4) Keep only journals with ≥3 papers in both groups
cnt_pro = prol_em_df['journal_name'].value_counts()
cnt_non = non_prol_em_df['journal_name'].value_counts()
common  = cnt_pro[cnt_pro >= 3].index.intersection(cnt_non[cnt_non >= 3].index)

emo_pro = emo_pro.loc[common]
emo_non = emo_non.loc[common]

# 5) Convert sums to percentages
prop_pro = emo_pro.div(cnt_pro, axis=0).loc[common] * 100
prop_non = emo_non.div(cnt_non, axis=0).loc[common] * 100

# 6) Plot side‑by‑side heatmaps
fig, axes = plt.subplots(1, 2, figsize=(16, 8), sharey=True)

sns.heatmap(
    prop_pro, ax=axes[0],
    cmap='YlGnBu', annot=False, fmt=".1f",
    cbar_kws={'label':'% of Emotions'}
)
axes[0].set_title('Emotion % by Journal (Prolific)')
axes[0].set_xlabel('Emotion')
axes[0].set_ylabel('Journal')

sns.heatmap(
    prop_non, ax=axes[1],
    cmap='YlGnBu', annot=False, fmt=".1f",
    cbar_kws={'label':'% of Emotions'}
)
axes[1].set_title('Emotion % by Journal (Non‑Prolific)')
axes[1].set_xlabel('Emotion')
axes[1].set_ylabel('')

plt.tight_layout()
plt.show()

# — Cell 14: Emotion Difference Heatmap —

import seaborn as sns
import matplotlib.pyplot as plt

# 1) Compute difference (Prolific % − Non‑Prolific %) — prop_pro and prop_non must exist
emotion_diff = prop_pro.subtract(prop_non, fill_value=0)

# 2) Plot heatmap of differences
plt.figure(figsize=(12, 8))
sns.heatmap(
    emotion_diff,
    cmap='RdBu_r',
    center=0,
    annot=False,
    fmt=".1f",
    cbar_kws={'label': 'Δ % Emotions (Prolific − Non‑Prolific)'}
)
plt.title('Emotion % Difference by Journal (Prolific − Non‑Prolific)')
plt.xlabel('Emotion')
plt.ylabel('Journal')
plt.tight_layout()
plt.show()

# — Cell 15: Grant–Paper Bipartite Network (PyVis) —

from pyvis.network import Network
import pandas as pd
import matplotlib.cm as cm
import matplotlib.colors as mcolors

# 1) Build a DataFrame of grant–paper edges
df['grant_information'] = df['grant_information'].fillna('').astype(str)
edges = []
for idx, grants in df['grant_information'].items():      # ← use .items() here
    for grant in grants.split(';'):
        grant = grant.strip()
        if grant and grant.lower() not in ('none', 'nan', ''):
            edges.append({'grant': grant, 'paper_id': f"Paper_{idx}"})

grant_edges_df = pd.DataFrame(edges)

# 2) Count papers per grant
grant_counts = grant_edges_df['grant'].value_counts()

# 3) Create color map & size scaling
cmap = cm.get_cmap('tab20', len(grant_counts))
grant_color_map = {
    grant: mcolors.rgb2hex(cmap(i))
    for i, grant in enumerate(grant_counts.index)
}
max_count = grant_counts.max()
grant_size_scaled = {
    grant: 10 + (count / max_count) * 40
    for grant, count in grant_counts.items()
}

# 4) Initialize PyVis network
net = Network(
    height="750px", width="100%",
    bgcolor="#ffffff", font_color="black",
    notebook=True
)

# 5) Add grant nodes
for grant, count in grant_counts.items():
    net.add_node(
        n_id=grant, label=grant,
        color=grant_color_map[grant],
        size=grant_size_scaled[grant],
        title=f"{grant} — {count} papers"
    )

# 6) Add paper nodes
for pid in grant_edges_df['paper_id'].unique():
    net.add_node(n_id=pid, label=pid, color='lightgreen', size=10)

# 7) Add edges
for _, row in grant_edges_df.iterrows():
    net.add_edge(row['grant'], row['paper_id'])

# 8) Display
net.show_buttons(filter_=['physics'])
net.show("grant_network.html")

# — Cell 16: Interactive Co‑Authorship Network via PyVis —

from pyvis.network import Network
from collections import Counter
import matplotlib.cm as cm
import matplotlib.colors as mcolors
import pandas as pd

# 1) Identify author columns and build edge list
author_cols = [c for c in df.columns if c.startswith('author_details.')]
edges = []
for _, row in df.iterrows():
    authors = [row[c] for c in author_cols if pd.notna(row[c]) and row[c] != '']
    for i in range(len(authors)):
        for j in range(i+1, len(authors)):
            edges.append((authors[i], authors[j]))

# 2) Compute publication counts per author
all_authors = pd.Series(df[author_cols].values.ravel()).dropna().astype(str)
author_counts = Counter(all_authors)

# 3) Prepare node sizes (10–50 px) and colors (categorical)
max_ct = max(author_counts.values())
size_map = {a: 10 + (cnt/max_ct)*40 for a,cnt in author_counts.items()}
cmap = cm.get_cmap('tab20', len(author_counts))
color_map = {a: mcolors.rgb2hex(cmap(i)) for i,a in enumerate(author_counts)}

# 4) Initialize PyVis network
net = Network(
    height="750px",
    width="100%",
    bgcolor="#ffffff",
    font_color="black",
    notebook=True
)

# 5) Add author nodes
for author, cnt in author_counts.items():
    net.add_node(
        n_id=author,
        label=author,
        size=size_map[author],
        color=color_map[author],
        title=f"{cnt} publications"
    )

# 6) Add co‑author edges
for a, b in edges:
    net.add_edge(a, b)

# 7) Show controls and render
net.show_buttons(filter_=['physics'])
net.show("coauthorship_network.html")